sudo: false
language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
matrix:
  exclude:
    - env: DJANGO="Django>=1.8,<1.9"
      python: "3.5"
    - env: DJANGO="Django>=1.9,<1.10"
      python: "3.3"

install: pip install $DJANGO
script: python setup.py test
