sudo: false
language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<2.0"
matrix:
  exclude:
    - env: DJANGO="Django>=1.8,<1.9"
      python: "3.5"

install: pip install $DJANGO
script: python setup.py test
